In [ ]:
!pip install SQLModel
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: SQLModel in /usr/local/lib/python3.10/dist-packages (0.0.22)
Requirement already satisfied: SQLAlchemy<2.1.0,>=2.0.14 in /usr/local/lib/python3.10/dist-packages (from SQLModel) (2.0.36)
Requirement already satisfied: pydantic<3.0.0,>=1.10.13 in /usr/local/lib/python3.10/dist-packages (from SQLModel) (2.9.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=1.10.13->SQLModel) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=1.10.13->SQLModel) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=1.10.13->SQLModel) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<2.1.0,>=2.0.14->SQLModel) (3.1.1)

En la siguiente sección se procederá a insertar las bases de datos adecuadas para realizar las conexiones con SQLModel, con ello en primer lugar

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
volcanes = pd.read_csv('/content/drive/MyDrive/DataBase_Volc_EarthQ/volcano.csv')
display(volcanes.head(10))

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,...,major_rock_5,minor_rock_1,minor_rock_2,minor_rock_3,minor_rock_4,minor_rock_5,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,...,,,,,,,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,...,,,,,,,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,...,,Basalt / Picro-Basalt,,,,,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,...,,,,,,,127863,127863,218469,2253483
4,321040,Adams,Stratovolcano,950,United States,Canada and Western USA,USA (Washington),46.206,-121.490,3742,...,,Dacite,,,,,0,70,4019,393303
5,283170,Adatarayama,Stratovolcano(es),1996,Japan,"Japan, Taiwan, Marianas",Honshu,37.647,140.281,1728,...,,Dacite,Basalt / Picro-Basalt,,,,428,3936,717078,5024654
6,221170,Adwa,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,10.070,40.840,1733,...,,,,,,,101,485,18645,1242922
7,221110,Afdera,Stratovolcano,Unknown,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,13.088,40.853,1250,...,,Basalt / Picro-Basalt,Trachybasalt / Tephrite Basanite,Andesite / Basaltic Andesite,,,51,6042,8611,161009
8,284160,Agrigan,Stratovolcano,1917,United States,"Japan, Taiwan, Marianas","Izu, Volcano, and Mariana Islands",18.770,145.670,965,...,,,,,,,0,0,0,0
9,342100,Agua,Stratovolcano,Unknown,Guatemala,México and Central America,Guatemala,14.465,-90.743,3760,...,,Dacite,,,,,9890,114404,2530449,7441660

In [14]:
erupciones = pd.read_csv('/content/drive/MyDrive/DataBase_Volc_EarthQ/eruptions.csv')
display(erupciones.head(10))
# Lista de erupciones integradas al número del volcán

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
5,273070,Taal,22344,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,22.0,14.002,120.993
6,282050,Kuchinoerabujima,22345,Confirmed Eruption,NaN,NaN,2020.0,1.0,11.0,Historical Observations,2020.0,4.0,17.0,30.443,130.217
7,241040,Whakaari/White Island,22338,Confirmed Eruption,1978/90 Crater Complex,2.0,2019.0,12.0,9.0,Historical Observations,2019.0,12.0,9.0,-37.520,177.180
8,311060,Semisopochnoi,22341,Confirmed Eruption,NaN,NaN,2019.0,12.0,7.0,Historical Observations,2020.0,3.0,15.0,51.930,179.580
9,284096,Nishinoshima,22340,Confirmed Eruption,NaN,1.0,2019.0,12.0,5.0,Historical Observations,2020.0,4.0,17.0,27.247,140.874

In [15]:
eventos = pd.read_csv('/content/drive/MyDrive/DataBase_Volc_EarthQ/events.csv')
display(eventos.head(10))
# Lista de eventos de erupciones

,volcano_number,volcano_name,eruption_number,eruption_start_year,event_number,event_type,event_remarks,event_date_year,event_date_month,event_date_day
0,210020,Chaine des Puys,10011,-4040,100001,Explosion,NaN,NaN,NaN,NaN
1,210020,Chaine des Puys,10011,-4040,100002,Scoria,NaN,NaN,NaN,NaN
2,210020,Chaine des Puys,10011,-4040,100003,Pyroclastic flow,NaN,NaN,NaN,NaN
3,210020,Chaine des Puys,10011,-4040,100004,Lava flow(s),NaN,NaN,NaN,NaN
4,210020,Chaine des Puys,10011,-4040,100005,Cinder cone formation,NaN,NaN,NaN,NaN
5,210020,Chaine des Puys,10011,-4040,100006,Pumice,NaN,NaN,NaN,NaN
6,210040,Calatrava Volcanic Field,10012,-3600,100008,Explosion,NaN,NaN,NaN,NaN
7,210040,Calatrava Volcanic Field,10012,-3600,100009,Pyroclastic flow,NaN,NaN,NaN,NaN
8,211003,Vulsini,10014,-104,100019,Flames,NaN,NaN,NaN,NaN
9,211004,Colli Albani,10015,-600,100021,Phreatic activity,Uncertain,NaN,NaN,NaN

In [16]:
volcanes.info()
erupciones.info()
eventos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   volcano_number            958 non-null    int64
 1   volcano_name              958 non-null    object
 2   primary_volcano_type      958 non-null    object
 3   last_eruption_year        958 non-null    object
 4   country                   958 non-null    object
 5   region                    958 non-null    object
 6   subregion                 958 non-null    object
 7   latitude                  958 non-null    float64
 8   longitude                 958 non-null    float64
 9   elevation                 958 non-null    int64
 10  tectonic_settings         958 non-null    object
 11  evidence_category         958 non-null    object
 12  major_rock_1              958 non-null    object
 13  major_rock_2              958 non-null    object
 14  major_rock_3              958 non-null    object
 15  major_rock_4              958 non-null    object
 16  major_rock_5              958 non-null    object
 17  minor_rock_1              958 non-null    object
 18  minor_rock_2              958 non-null    object
 19  minor_rock_3              958 non-null    object
 20  minor_rock_4              958 non-null    object
 21  minor_rock_5              958 non-null    object
 22  population_within_5_km    958 non-null    int64
 23  population_within_10_km   958 non-null    int64
 24  population_within_30_km   958 non-null    int64
 25  population_within_100_km  958 non-null    int64
dtypes: float64(2), int64(6), object(18)
memory usage: 194.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11178 entries, 0 to 11177
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   volcano_number          11178 non-null  int64
 1   volcano_name            11178 non-null  object
 2   eruption_number         11178 non-null  int64
 3   eruption_category       11178 non-null  object
 4   area_of_activity        4694 non-null   object
 5   vei                     8272 non-null   float64
 6   start_year              11177 non-null  float64
 7   start_month             10985 non-null  float64
 8   start_day               10982 non-null  float64
 9   evidence_method_dating  9898 non-null   object
 10  end_year                4332 non-null   float64
 11  end_month               4329 non-null   float64
 12  end_day                 4326 non-null   float64
 13  latitude                11178 non-null  float64
 14  longitude               11178 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 1.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41322 entries, 0 to 41321
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   volcano_number       41322 non-null  int64
 1   volcano_name         41322 non-null  object
 2   eruption_number      41322 non-null  int64
 3   eruption_start_year  41322 non-null  int64
 4   event_number         41322 non-null  int64
 5   event_type           41322 non-null  object
 6   event_remarks        4880 non-null   object
 7   event_date_year      10007 non-null  float64
 8   event_date_month     7132 non-null   float64
 9   event_date_day       5923 non-null   float64
dtypes: float64(3), int64(4), object(3)
memory usage: 3.2+ MB

In [17]:
eventos = eventos.drop('event_remarks', axis=1)
volcanes = volcanes.drop(columns=['major_rock_2','major_rock_3','major_rock_4','major_rock_5','minor_rock_1','minor_rock_2','minor_rock_3','minor_rock_4','minor_rock_5'], axis=1)
erupciones = erupciones.drop('area_of_activity', axis=1)
display(volcanes.head(4))
display(erupciones.head(5))
display(eventos.head(5))

,volcano_number,volcano_name,primary_volcano_type,last_eruption_year,country,region,subregion,latitude,longitude,elevation,tectonic_settings,evidence_category,major_rock_1,population_within_5_km,population_within_10_km,population_within_30_km,population_within_100_km
0,283001,Abu,Shield(s),-6850,Japan,"Japan, Taiwan, Marianas",Honshu,34.500,131.600,641,Subduction zone / Continental crust (>25 km),Eruption Dated,Andesite / Basaltic Andesite,3597,9594,117805,4071152
1,355096,Acamarachi,Stratovolcano,Unknown,Chile,South America,"Northern Chile, Bolivia and Argentina",-23.292,-67.618,6023,Subduction zone / Continental crust (>25 km),Evidence Credible,Dacite,0,7,294,9092
2,342080,Acatenango,Stratovolcano(es),1972,Guatemala,México and Central America,Guatemala,14.501,-90.876,3976,Subduction zone / Continental crust (>25 km),Eruption Observed,Andesite / Basaltic Andesite,4329,60730,1042836,7634778
3,213004,Acigol-Nevsehir,Caldera,-2080,Turkey,Mediterranean and Western Asia,Turkey,38.537,34.621,1683,Intraplate / Continental crust (>25 km),Eruption Dated,Rhyolite,127863,127863,218469,2253483

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550

,volcano_number,volcano_name,eruption_number,eruption_start_year,event_number,event_type,event_date_year,event_date_month,event_date_day
0,210020,Chaine des Puys,10011,-4040,100001,Explosion,NaN,NaN,NaN
1,210020,Chaine des Puys,10011,-4040,100002,Scoria,NaN,NaN,NaN
2,210020,Chaine des Puys,10011,-4040,100003,Pyroclastic flow,NaN,NaN,NaN
3,210020,Chaine des Puys,10011,-4040,100004,Lava flow(s),NaN,NaN,NaN
4,210020,Chaine des Puys,10011,-4040,100005,Cinder cone formation,NaN,NaN,NaN

In [20]:
# Calculando el primer cuartil (Q1) para la columna 'vei', ignorando los valores NaN
q1_vei = erupciones['vei'].quantile(0.25)

# Llenando los valores NaN en la columna 'vei' con el Q1 calculado
erupciones['vei'].fillna(q1_vei, inplace=True)

# DataFrame actualizado para verificación
display(erupciones.head(10))

<ipython-input-20-20c19ed14fff>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  erupciones['vei'].fillna(q1_vei, inplace=True)

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,1.0,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,1.0,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,1.0,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,1.0,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,1.0,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550
5,273070,Taal,22344,Confirmed Eruption,1.0,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,22.0,14.002,120.993
6,282050,Kuchinoerabujima,22345,Confirmed Eruption,1.0,2020.0,1.0,11.0,Historical Observations,2020.0,4.0,17.0,30.443,130.217
7,241040,Whakaari/White Island,22338,Confirmed Eruption,2.0,2019.0,12.0,9.0,Historical Observations,2019.0,12.0,9.0,-37.520,177.180
8,311060,Semisopochnoi,22341,Confirmed Eruption,1.0,2019.0,12.0,7.0,Historical Observations,2020.0,3.0,15.0,51.930,179.580
9,284096,Nishinoshima,22340,Confirmed Eruption,1.0,2019.0,12.0,5.0,Historical Observations,2020.0,4.0,17.0,27.247,140.874

In [21]:
selected_eruptions = erupciones.iloc[342:356]  # Corte desde el índice 342 hasta (pero sin incluir) 356
display(selected_eruptions)

,volcano_number,volcano_name,eruption_number,eruption_category,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
342,221041,Dallol,20939,Confirmed Eruption,0.0,2011.0,1.0,4.0,Historical Observations,2011.0,1.0,4.0,14.242,40.300
343,263310,Tengger Caldera,16064,Confirmed Eruption,3.0,2010.0,11.0,26.0,Historical Observations,2012.0,6.0,13.0,-7.942,112.950
344,352080,Tungurahua,11645,Confirmed Eruption,3.0,2010.0,11.0,22.0,Historical Observations,2011.0,1.0,2.0,-1.467,-78.442
345,300230,Kizimen,19264,Confirmed Eruption,3.0,2010.0,11.0,11.0,Historical Observations,2013.0,9.0,13.0,55.131,160.320
346,273010,Bulusan,16772,Confirmed Eruption,2.0,2010.0,11.0,6.0,Historical Observations,2011.0,5.0,13.0,12.769,124.056
347,263250,Merapi,15925,Confirmed Eruption,4.0,2010.0,10.0,26.0,Historical Observations,2012.0,7.0,15.0,-7.540,110.446
348,262000,Krakatau,15634,Confirmed Eruption,2.0,2010.0,10.0,25.0,Historical Observations,2011.0,3.0,9.0,-6.102,105.423
349,233020,"Fournaise, Piton de la",14392,Confirmed Eruption,1.0,2010.0,10.0,14.0,Historical Observations,2010.0,12.0,10.0,-21.244,55.708
350,290240,Sarychev Peak,18820,Uncertain Eruption,2.0,2010.0,9.0,20.0,NaN,2010.0,9.0,20.0,48.092,153.200
351,260010,Barren Island,15388,Confirmed Eruption,2.0,2010.0,9.0,17.0,Historical Observations,2011.0,6.0,22.0,12.278,93.858
352,311240,Cleveland,19820,Uncertain Eruption,2.0,2010.0,9.0,12.0,NaN,2010.0,9.0,26.0,52.825,-169.944
353,357040,Planchon-Peteroa,11947,Confirmed Eruption,2.0,2010.0,9.0,6.0,Historical Observations,2010.0,10.0,13.0,-35.223,-70.568
354,261080,Sinabung,15404,Confirmed Eruption,2.0,2010.0,8.0,27.0,Historical Observations,2010.0,9.0,18.0,3.170,98.392
355,211060,Etna,13854,Confirmed Eruption,1.0,2010.0,8.0,25.0,Historical Observations,2013.0,4.0,27.0,37.748,14.999